---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: qbrr

before:
  hooks:
    - go mod tidy

builds:
  - id: qbrr
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/qbrr/main.go
    binary: qbrr

archives:
  - id: qbrr
    ids:
      - qbrr
    format_overrides:
      - goos: windows
        formats: ['zip']

upx:
  - enabled: true
    compress: best
    lzma: true
